### ISSUE TITLE
Model classes (State, User, ToDo, Task)

### ISSUE THREAD

**Issue by RMuskovets** [it-acad/hibernate-1-sprint-13-team-3-3#1]
* [ ] **Not done**

### DB structure
<img width="597" alt="Screenshot 2020-10-21 at 17 21 01" src="https://user-images.githubusercontent.com/24433702/104206030-c03ba180-5437-11eb-93aa-e0fa70400ac6.png">

### `State`
* [ ] `id` field
* [ ] `name` field
* [ ] getter for `id`
* [ ] getter for `name`
* [ ] setter for `name`
* [ ] `equals()`
* [ ] `hashCode()`
* [ ] constructor w/o params
* [ ] `toString()`
### `User`
* [x] `id` field
* [x] `email` field
* [x] `firstName` field
* [x] `lastName` field
* [x] `password` field
* [x] `role` field (`Role`, `optional` = `false`)
* [x] `equals()`
* [x] `hashCode()`
* [x] constructor w/o params
* [x] `toString()`
### `ToDo`
* [x] `id` field
* [x] `created_at` field
* [x] `title` field
* [x] `owner` field (`User`, `@ManyToOne`)
* [x] `tasks` field (`List<Task>`, `@OneToMany`)
* [x] `collaborators` field (`List<User>`, `@ManyToMany`)
* [x] `equals()`
* [x] `hashCode()`
* [x] constructor w/o params
* [x] `toString()`
### `Task`
* [ ] `id` field
* [ ] `name` field
* [ ] `priority` field
* [ ] `todo` field (`@ManyToOne`, `ToDo`)
* [ ] `state` field (`@OneToOne`, `State`)
* [ ] `equals()`
* [ ] `hashCode()`
* [ ] constructor w/o params
* [ ] `toString()`

## Templates? idk
* `id`:
  ```java
  @Id @GeneratedValue(generator = "sequence-generator")
  @GenericGenerator(
      name = "sequence-generator",
      strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator",
      parameters = {
          @Parameter(name = "sequence_name", value = "ENTITY_sequence"),
          @Parameter(name = "initial_value", value = "10"),
          @Parameter(name = "increment_size", value = "1")
      })
  private long id;
  ```
